### PR TITLE
Example #ProgressiveEnhancement

### PR DESCRIPTION
**Pull request by nelsonic**
register-1of4

register-3of4

### CODE REVIEW

**Comment by nelsonic** [comment]
Avoids Cross Site Scripting:
register-hack-1of2

**Comment by nelsonic** [comment]
Displays welcome message on successful registration:
reg-success-1of2

**Comment by nelsonic** [comment]
Need to get this merged into master for the code climate to work ...
@edwardcodes please review & merge. thanks!

**Comment by ghost** [comment]
Looks good. Tests pass. Merging.

**Pull request merged**
