### PR TITLE
Change clone instructions to use HTTPS

### PR DESCRIPTION
**Pull request by roryc89**
Allows anyone to clone without authenication

### CODE REVIEW

**Comment by iteles** [comment]
The question we need to askis do we _want_ to **encourage** people to do this? Do you have a preference for doing it this way @roryc89?

**Comment by roryc89** [comment]
@iteles Some people who do not realise they need to be authenticated and fail to clone may be put off the tutorial. I don't see any downside. Just a thought

**Comment by nelsonic** [comment]
@roryc89 thanks for the update. 
you're right, we don't want anyone to be put off trying something because of a git fail.
merging. :+1:

**Comment by iteles** [comment]
:+1:

**Comment by roryc89** [comment]
no worries :)

**Pull request merged**
