### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by nelsonic**
@iteles another micro-update.
No code changed. ( _it was already pretty good..._ :stuck_out_tongue_winking_eye: )
Thanks.

### CODE REVIEW

**Comment by nelsonic** [comment]
Oh... `bcrypt` is not happy on Node 4.2 ... need to debug. @iteles please ignore PR for now. thanks.

**Comment by iteles** [comment]
OK :+1:

**Comment by nelsonic** [comment]
@iteles it isn't _pretty_ ...
But until Travis CI update their _default_ version of GCC to 4.8+ see: 
https://github.com/travis-ci/travis-ci/issues/1379

We are forced to _manually_ install the latest compiler for `bcrypt` to work. :disappointed: 

I got the `.travis.yml` script from: https://github.com/ncb000gt/node.bcrypt.js/blob/ebd1d5e89d381d5f7c774663c216567b4568596c/.travis.yml

**Comment by iteles** [comment]
Yuk. At least it's only a few lines...!
Good find though.

**Pull request merged**
